
name: Test Automation Workflow
on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Maven Test
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.5.0
      with:
        name: Test Log 
        path: logs/
    - name: Upload Extent Reports
      if: always()
      uses: actions/upload-artifact@v4.5.0
      with:
        name: Extent Report Artifacts
        path: report.html
    - name: Test Status
      run: echo "Test Execution Completed" 
